### PR TITLE
feat: Quick fix to store vc credential

### LINKED ISSUE #50: Quick fix to store vc credential

### PR DESCRIPTION
**Pull request by talwinder50**
closes #50

Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>

### CODE REVIEW

File: pkg/restapi/vc/operation/operations.go [hunk 1]
```diff
@@ -240,7 +240,7 @@ func (o *Operation) storeVCHandler(rw http.ResponseWriter, req *http.Request) {
 
 	doc := operation.StructuredDocument{}
 	doc.Content = make(map[string]interface{})
-	doc.Content["message"] = data
+	doc.Content["message"] = data.Credential
```
Comment (sandrask) [inline pkg/restapi/vc/operation/operations.go]: You will probably need to use MarshalJSON instead of struct
