### PR TITLE
feat: Fix the cmd vc-rest unit-test

### LINKED ISSUE #36: Fix the cmd vc-rest unit-test

### PR DESCRIPTION
**Pull request by talwinder50**
closes #36

Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>

### CODE REVIEW

File: cmd/vc-rest/startcmd/start.go [hunk 1]
```diff
@@ -95,6 +96,10 @@ func startEdgeService(parameters *vcRestParameters) error {
 		return errMissingHostURL
 	}
 
+	if parameters.edvURL == "" {
```
Comment (DRK3) [inline cmd/vc-rest/startcmd/start.go]: You can add a unit test for this. Call it TestStartCmdWithBlankEDVArg()

Comment (talwinder50) [reply cmd/vc-rest/startcmd/start.go]: done

Comment (talwinder50) [reply cmd/vc-rest/startcmd/start.go]: done
