### PR TITLE
fix: JSON-LD strict mode VC validation

### LINKED ISSUE #340: Issuer and Holder validation should be URI.
The plugfest test suite description was updated to declare that the validation test is for a URI (not limited to a DID).

### PR DESCRIPTION
**Pull request by rolsonquadras**
part of  #327  

Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

### CODE REVIEW

File: pkg/restapi/vc/operation/operations.go [hunk 1]
```diff
@@ -1537,7 +1537,7 @@ func getPresentationSigningOpts(opts *SignPresentationOptions) []crypto.SigningO
 }
 
 func (o *Operation) validateCredentialProof(vcByte []byte, opts *CredentialsVerificationOptions) error {
-	vc, err := o.parseAndVerifyVC(vcByte)
+	vc, err := o.parseAndVerifyVCStrictMode(vcByte)
```
Comment (troyronda) [inline pkg/restapi/vc/operation/operations.go:1540]: what about VPs

Comment (rolsonquadras) [reply pkg/restapi/vc/operation/operations.go:1540]: Currently, no options available for VP - 

https://github.com/hyperledger/aries-framework-go/blob/7fc555ef6cb0aa37b5d4af0f43061eafc801fdc6/pkg/doc/verifiable/presentation.go#L312-L315
cc : @kdimak
